# Prometheus Alert Rules for Gmail Rich Email Integration - V2
# Sprint 54 Phase 4: Observability (Production-Grade)
#
# Label Standardization:
# - service: "relay" (top-level service name)
# - component: "gmail" | "rollout" | "validation" | "mime" | "metrics"
# - provider: "google" (for provider-specific alerts)
# - action: "gmail.send" (for action-specific alerts)
#
# Alert Tiers:
# - WARNING (1% error rate / 500ms latency): Early warning, Slack notification
# - CRITICAL (5% error rate / 2s latency): Page-worthy, PagerDuty escalation
# - INFO: Context/awareness, low-noise channel

groups:
- name: gmail_send_alerts
  rules:
  # ========================================
  # Error Rate Alerts (Multi-Window SLO)
  # ========================================

  # Fast burn: 5% budget consumed in 1 hour (page immediately)
  - alert: GmailSendErrorBudgetFastBurn
    expr: |
      (job:gmail_send_exec_rate:5m > 0.1)
      and
      (
        sum(rate(action_error_total{provider="google",action="gmail.send"}[5m]))
        / clamp_min(sum(rate(action_exec_total{provider="google",action="gmail.send"}[5m])), 1)
      ) > 0.01
      and
      (
        sum(rate(action_error_total{provider="google",action="gmail.send"}[1h]))
        / clamp_min(sum(rate(action_exec_total{provider="google",action="gmail.send"}[1h])), 1)
      ) > 0.01
    for: 5m
    labels:
      severity: critical
      service: relay
      component: gmail
      provider: google
      action: gmail.send
      slo_type: error_rate
    annotations:
      summary: "Gmail error budget fast burn >1% (page)"
      description: "Error rate {{ $value | humanizePercentage }} sustained over 1h (5m + 1h windows, fast SLO burn)"
      runbook_url: "docs/observability/PHASE-4-OBSERVABILITY-SETUP.md#error-budget-burn"
      dashboard_url: "https://grafana/d/gmail-integration/overview"

  # Slow burn: 1% budget consumed in 6 hours (create ticket)
  - alert: GmailSendErrorBudgetSlowBurn
    expr: |
      (job:gmail_send_exec_rate:5m > 0.1)
      and
      (
        sum(rate(action_error_total{provider="google",action="gmail.send"}[1h]))
        / clamp_min(sum(rate(action_exec_total{provider="google",action="gmail.send"}[1h])), 1)
      ) > 0.01
      and
      (
        sum(rate(action_error_total{provider="google",action="gmail.send"}[6h]))
        / clamp_min(sum(rate(action_exec_total{provider="google",action="gmail.send"}[6h])), 1)
      ) > 0.01
    for: 30m
    labels:
      severity: warning
      service: relay
      component: gmail
      provider: google
      action: gmail.send
      slo_type: error_rate
    annotations:
      summary: "Gmail error budget slow burn >1% (ticket)"
      description: "Error rate {{ $value | humanizePercentage }} sustained over 6h (1h + 6h windows, slow SLO burn)"
      runbook_url: "docs/observability/PHASE-4-OBSERVABILITY-SETUP.md#error-budget-burn"
      dashboard_url: "https://grafana/d/gmail-integration/overview"

  # Simple threshold alerts (original, kept for simplicity)
  - alert: GmailSendHighErrorRateWarning
    expr: (job:gmail_send_exec_rate:5m > 0.1) and (job:gmail_send_errors_rate:5m > 0.01)
    for: 10m
    labels:
      severity: warning
      service: relay
      component: gmail
      provider: google
      action: gmail.send
    annotations:
      summary: "Gmail send error rate >1% (warn)"
      description: "Error rate is {{ $value | humanizePercentage }} over the last 5 minutes (threshold: 1%, traffic: {{ query `job:gmail_send_exec_rate:5m` | first | value | humanize }}req/s)"
      runbook_url: "docs/observability/PHASE-4-OBSERVABILITY-SETUP.md#gmail-sends"
      dashboard_url: "https://grafana/d/gmail-integration/overview"

  - alert: GmailSendHighErrorRateCritical
    expr: (job:gmail_send_exec_rate:5m > 0.1) and (job:gmail_send_errors_rate:5m > 0.05)
    for: 10m
    labels:
      severity: critical
      service: relay
      component: gmail
      provider: google
      action: gmail.send
    annotations:
      summary: "Gmail send error rate >5% (critical)"
      description: "Error rate is {{ $value | humanizePercentage }} over the last 5 minutes (threshold: 5%, traffic: {{ query `job:gmail_send_exec_rate:5m` | first | value | humanize }}req/s)"
      runbook_url: "docs/observability/PHASE-4-OBSERVABILITY-SETUP.md#gmail-sends"
      dashboard_url: "https://grafana/d/gmail-integration/overview"

  # ========================================
  # Latency Alerts (P95)
  # ========================================

  - alert: GmailSendHighLatencyWarning
    expr: job:gmail_send_latency_p95:5m > 0.5
    for: 10m
    labels:
      severity: warning
      service: relay
      component: gmail
      provider: google
      action: gmail.send
    annotations:
      summary: "Gmail send P95 > 500ms (warn)"
      description: "P95 latency is {{ $value }}s (threshold: 0.5s)"
      runbook_url: "docs/observability/PHASE-4-OBSERVABILITY-SETUP.md#latency"
      dashboard_url: "https://grafana/d/gmail-integration/overview"

  - alert: GmailSendHighLatencyCritical
    expr: job:gmail_send_latency_p95:5m > 2.0
    for: 10m
    labels:
      severity: critical
      service: relay
      component: gmail
      provider: google
      action: gmail.send
    annotations:
      summary: "Gmail send P95 > 2s (critical)"
      description: "P95 latency is {{ $value }}s (threshold: 2.0s)"
      runbook_url: "docs/observability/PHASE-4-OBSERVABILITY-SETUP.md#latency"
      dashboard_url: "https://grafana/d/gmail-integration/overview"

  # ========================================
  # Rollout Controller Health
  # ========================================

  - alert: RolloutControllerStalled
    expr: absent_over_time(rollout_controller_runs_total{status="ok"}[60m])
    for: 5m
    labels:
      severity: warning
      service: relay
      component: rollout
    annotations:
      summary: "No successful controller runs in 60m"
      description: "Rollout controller hasn't completed a successful run in the last hour (avoids false positives during low-traffic windows)"
      runbook_url: "docs/evidence/sprint-54/CONTROLLER-USAGE.md#troubleshooting"
      dashboard_url: "https://grafana/d/rollout-controller/monitoring"

  - alert: RolloutControllerFailing
    expr: increase(rollout_controller_runs_total{status!="ok"}[15m]) > 0
    for: 5m
    labels:
      severity: warning
      service: relay
      component: rollout
    annotations:
      summary: "Controller failures observed in last 15m"
      description: "Rollout controller has {{ $value }} failed runs in the last 15 minutes"
      runbook_url: "docs/evidence/sprint-54/CONTROLLER-USAGE.md#troubleshooting"
      dashboard_url: "https://grafana/d/rollout-controller/monitoring"

  # ========================================
  # Validation Error Spike
  # ========================================

  - alert: GmailValidationErrorSpike
    expr: job:structured_error_rate_total:5m > 0.10
    for: 10m
    labels:
      severity: info
      service: relay
      component: validation
      provider: google
    annotations:
      summary: "Structured validation errors >10% of traffic"
      description: "{{ $value | humanizePercentage }} of requests are failing validation (may indicate client issue)"
      runbook_url: "docs/observability/PHASE-4-OBSERVABILITY-SETUP.md#structured-errors"
      dashboard_url: "https://grafana/d/errors/structured-errors"

  # ========================================
  # MIME Builder Performance
  # ========================================

  - alert: MimeBuilderSlowPerformance
    expr: job:gmail_mime_build_p95:5m > 0.5
    for: 10m
    labels:
      severity: warning
      service: relay
      component: mime
      provider: google
    annotations:
      summary: "MIME build P95 > 500ms"
      description: "P95 MIME build time is {{ $value }}s (threshold: 0.5s)"
      runbook_url: "docs/observability/PHASE-4-OBSERVABILITY-SETUP.md#mime-performance"
      dashboard_url: "https://grafana/d/gmail-integration/overview"

  # ========================================
  # HTML Sanitization Anomaly
  # ========================================

  - alert: HighSanitizationActivity
    expr: sum(rate(gmail_html_sanitization_changes_total[5m])) > 50
    for: 5m
    labels:
      severity: info
      service: relay
      component: sanitization
      provider: google
    annotations:
      summary: "High HTML sanitization activity (possible hostile input burst)"
      description: "{{ $value | humanize }} sanitization changes/sec (threshold: 50/sec, evaluated over 5m window)"
      runbook_url: "docs/observability/PHASE-4-OBSERVABILITY-SETUP.md#sanitization"
      dashboard_url: "https://grafana/d/gmail-integration/overview"

  # ========================================
  # Metrics Collection Health (Sentinel)
  # ========================================

  - alert: GmailMetricsMissing
    expr: absent(job:gmail_send_exec_rate:5m)
    for: 15m
    labels:
      severity: critical
      service: relay
      component: metrics
    annotations:
      summary: "Gmail metrics not being collected"
      description: "No Gmail send execution rate metrics for 15+ minutes (Prometheus scrape failure or app down)"
      runbook_url: "docs/observability/PHASE-4-OBSERVABILITY-SETUP.md#metrics-missing"
      dashboard_url: "https://grafana/d/gmail-integration/overview"
