name: Rollout Controller

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  rollout:
    runs-on: ubuntu-latest
    # Only run if PROMETHEUS_BASE_URL is configured
    if: vars.PROMETHEUS_BASE_URL != ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install redis httpx
          pip install -e .

      - name: Run rollout controller
        env:
          PROMETHEUS_BASE_URL: ${{ vars.PROMETHEUS_BASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          ROLLOUT_DRY_RUN: ${{ vars.ROLLOUT_DRY_RUN || 'false' }}
        run: |
          python scripts/rollout_controller.py

      - name: Commit audit log updates
        if: success()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Check if rollout_log.md was updated
          if [[ -f docs/evidence/sprint-54/rollout_log.md ]]; then
            git add docs/evidence/sprint-54/rollout_log.md

            # Only commit if there are changes
            if ! git diff --cached --quiet; then
              git commit -m "chore: Update rollout audit log [skip ci]"
              git push
            else
              echo "No changes to rollout log"
            fi
          else
            echo "No rollout log file found"
          fi

      - name: Upload controller logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rollout-controller-logs-${{ github.run_id }}
          path: |
            docs/evidence/sprint-54/rollout_log.md
          if-no-files-found: ignore
