name: Rollout Controller Nudge

on:
  schedule:
    # Every Monday at 14:00 UTC (weekly nudge)
    - cron: '0 14 * * MON'
  workflow_dispatch:  # Allow manual trigger

jobs:
  nudge:
    runs-on: ubuntu-latest
    # Only run on main branch when explicitly enabled
    if: ${{ github.ref == 'refs/heads/main' && vars.NUDGE_ENABLED == 'true' }}

    concurrency:
      group: rollout-nudge
      cancel-in-progress: false

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Post reminder issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "⏰ Reminder: Rollout Controller Weekly Nudge (Sprint ${{ vars.SPRINT_NUMBER || 'TBD' }})"
          content-filepath: docs/evidence/sprint-54/OBSERVATION-WINDOW-START.md
          labels: |
            phase:ops
            priority:p2
            area:rollout
            type:reminder
          assignees: kmabbott81

      - name: Log reminder
        run: |
          echo "📬 Weekly rollout nudge triggered"
          echo ""
          echo "To enable rollout controller:"
          echo "  1. Deploy Prometheus stack (Docker Compose or Railway)"
          echo "  2. Set ROLLOUT_CONTROLLER_ENABLED=true in GitHub repo variables"
          echo "  3. Set PROMETHEUS_BASE_URL and REDIS_URL"
          echo "  4. Run controller for 24-48h observation"
          echo ""
          echo "To disable this nudge: Set NUDGE_ENABLED=false in repo variables"
